### ISSUE TITLE
Mod Crashes on Linux

### ISSUE THREAD

**Issue by RoY7x** [RuiNtD/SVRichPresence#54]
Got an issue when I first downloaded this with it crashing on startup.

I am using arch linux with SMAPI 4.1.7 with Stardew Valley 1.6.14 build 24317 on Unix 6.11.7.1

I get the following error message at launch

```
[Rich Presence] Mod crashed on entry and might not work correctly. Technical details:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'xdg-mime' with working directory '/home/roy/.local/share/Steam/steamapps/common/Stardew Valley'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at DiscordRPC.Registry.UnixUriSchemeCreator.RegisterMime(String appid)
   at DiscordRPC.Registry.UnixUriSchemeCreator.RegisterUriScheme(UriSchemeRegister register)
   at DiscordRPC.Registry.UriSchemeRegister.RegisterUriScheme()
   at DiscordRPC.DiscordRpcClient.RegisterUriScheme(String steamAppID, String executable)
   at SVRichPresence.RichPresenceMod.Entry(IModHelper helper) in E:\dev\myprojs\SVRichPresence\RichPresenceMod.cs:line 35
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/SCore.cs:line 1860

```

**Comment by RuiNtD** [comment]
Hello. Unfortunately, Linux is untested and unsupported, but it looks like it's trying to call `xdg-mime`, which is missing from your system. According to Google, that should be in the [xdg-mime](https://archlinux.org/packages/extra/any/xdg-utils/) package. Make sure that's installed.

**Comment by 42willow** [comment]
This mod was working for me on Linux previously... what happened to https://github.com/RuiNtD/SVRichPresence/issues/5#issuecomment-984985845 ?

**Comment by RuiNtD** [comment]
> what happened to [#5 (comment)](https://github.com/RuiNtD/SVRichPresence/issues/5#issuecomment-984985845) ?

That comment is from 3 years ago. Linux is hard for me to test, so I've just been hoping it doesn't break. 😅 
Since your issue is likely something different, can you post your log in a new ticket?

**Comment by RuiNtD** [comment]
@RoY7x I'm closing this ticket as stale. If you're still having issues, feel free to comment.

**Comment by 42willow** [comment]
I am getting the same error message :sweat_smile:

**Comment by RuiNtD** [comment]
Hello. I just uploaded 3.0.3 which should hopefully fix this particular crash. Keep in mind SVRP is still untested on Linux. Also, Steam Deck is unsupported due to the inability to install Discord as a native package, which is required for RPC.
